#!/usr/bin/env python3
"""
Build NodeTable master table XLSX and CSV exports (v0.1 baseline for S03 planning).
Outputs (all deterministic, overwritten on each run):
  - nodetable_master_table_v0_1.xlsx
  - fields_v0_1.csv, packets_v0_1.csv, sources_v0_1.csv
No network; reads only local paths (script uses embedded data from canon/code/research).
"""

from __future__ import annotations

import csv
from pathlib import Path

try:
    from openpyxl import Workbook
except ImportError:
    raise SystemExit("Install openpyxl: pip install openpyxl")

# Output paths: master_table/ directory
SCRIPT_DIR = Path(__file__).resolve().parent
MASTER_TABLE_DIR = SCRIPT_DIR.parent
OUTPUT_XLSX = MASTER_TABLE_DIR / "nodetable_master_table_v0_1.xlsx"
OUTPUT_CSV_FIELDS = MASTER_TABLE_DIR / "fields_v0_1.csv"
OUTPUT_CSV_PACKETS = MASTER_TABLE_DIR / "packets_v0_1.csv"
OUTPUT_CSV_SOURCES = MASTER_TABLE_DIR / "sources_v0_1.csv"

FIELDS_HEADERS = [
    "field_key",
    "scope_class",
    "knowledge_category",
    "status",
    "owner",
    "in_node_entry_struct",
    "node_entry_member",
    "persisted",
    "persistence_notes",
    "exported_over_ble",
    "ble_record_offset",
    "ble_bytes",
    "sent_on_air",
    "packet_name_canon",
    "on_air_contract_ref",
    "wire_bytes_fixed",
    "wire_optional",
    "logical_type",
    "units_scaling",
    "min_value",
    "max_value",
    "bits_needed_min",
    "tier",
    "default_cadence",
    "trigger_type",
    "threshold_rule",
    "staleness_ttl_hint",
    "notes",
]

# One row per field. Empty string = leave blank. Source: NodeEntry + BLE 26-byte + canon inventory + research/mesh future.
# BLE record: 0-7 node_id, 8-9 short_id, 10 flags, 11-12 last_seen_age_s, 13-16 lat_e7, 17-20 lon_e7, 21-22 pos_age_s, 23 last_rx_rssi, 24-25 last_seq.
FIELDS_ROWS = [
    # --- CodeNow + Canon: identity & core ---
    {
        "field_key": "payloadVersion",
        "scope_class": "Core",
        "knowledge_category": "Identity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "all Node_*",
        "on_air_contract_ref": "beacon_payload_encoding_v0 §3",
        "wire_bytes_fixed": "1",
        "wire_optional": "MUST",
        "logical_type": "u8",
        "units_scaling": "0x00=v0",
        "min_value": "0",
        "max_value": "255",
        "bits_needed_min": "8",
        "tier": "A Core",
        "default_cadence": "every beacon tick",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Payload format version; first byte of payload.",
    },
    {
        "field_key": "node_id",
        "scope_class": "Core",
        "knowledge_category": "Identity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "node_id",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "0",
        "ble_bytes": "8",
        "sent_on_air": "Y",
        "packet_name_canon": "all Node_*",
        "on_air_contract_ref": "beacon_payload_encoding_v0 §3",
        "wire_bytes_fixed": "6",
        "wire_optional": "MUST",
        "logical_type": "u48",
        "units_scaling": "6-byte LE MAC48",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "48",
        "tier": "A Core",
        "default_cadence": "every beacon tick",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Primary key; domain uint64 lower 48 bits.",
    },
    {
        "field_key": "seq16",
        "scope_class": "Core",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_seq",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "24",
        "ble_bytes": "2",
        "sent_on_air": "Y",
        "packet_name_canon": "all Node_*",
        "on_air_contract_ref": "beacon_payload_encoding_v0 §3; field_cadence_v0 §2",
        "wire_bytes_fixed": "2",
        "wire_optional": "MUST",
        "logical_type": "u16",
        "units_scaling": "LE; global per-node counter",
        "min_value": "0",
        "max_value": "65535",
        "bits_needed_min": "16",
        "tier": "A Core",
        "default_cadence": "every beacon tick",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Dedupe key (nodeId48, seq16). last_seq in NodeEntry.",
    },
    {
        "field_key": "positionLat",
        "scope_class": "Core",
        "knowledge_category": "Position",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "lat_e7",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "13",
        "ble_bytes": "4",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Pos",
        "on_air_contract_ref": "beacon_payload_encoding_v0 §4.1",
        "wire_bytes_fixed": "3",
        "wire_optional": "MUST",
        "logical_type": "u24",
        "units_scaling": "lat_u24 packed; domain 1e-7 deg",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "24",
        "tier": "A Core",
        "default_cadence": "every beacon tick when position valid",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Core only with valid fix. BLE exports lat_e7 (i32).",
    },
    {
        "field_key": "positionLon",
        "scope_class": "Core",
        "knowledge_category": "Position",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "lon_e7",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "17",
        "ble_bytes": "4",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Pos",
        "on_air_contract_ref": "beacon_payload_encoding_v0 §4.1",
        "wire_bytes_fixed": "3",
        "wire_optional": "MUST",
        "logical_type": "u24",
        "units_scaling": "lon_u24 packed; domain 1e-7 deg",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "24",
        "tier": "A Core",
        "default_cadence": "every beacon tick when position valid",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Core only with valid fix. BLE exports lon_e7 (i32).",
    },
    {
        "field_key": "short_id",
        "scope_class": "Informative",
        "knowledge_category": "Identity",
        "status": "CodeNow",
        "owner": "Derived",
        "in_node_entry_struct": "Y",
        "node_entry_member": "short_id",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "8",
        "ble_bytes": "2",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u16",
        "units_scaling": "CRC16-CCITT over node_id LE",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Display only; not protocol key. Reserved 0x0000/0xFFFF handled.",
    },
    {
        "field_key": "is_self",
        "scope_class": "Informative",
        "knowledge_category": "LocalOnly",
        "status": "CodeNow",
        "owner": "AppLocal",
        "in_node_entry_struct": "Y",
        "node_entry_member": "is_self",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot (flags bit0)",
        "exported_over_ble": "Y",
        "ble_record_offset": "10",
        "ble_bytes": "1",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "flags bit 0x01",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "1",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    {
        "field_key": "pos_valid",
        "scope_class": "Core",
        "knowledge_category": "Position",
        "status": "CodeNow",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "pos_valid",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot (flags bit1)",
        "exported_over_ble": "Y",
        "ble_record_offset": "10",
        "ble_bytes": "1",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "flags bit 0x02; Core implies valid",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "1",
        "tier": "A Core",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Domain/BLE only; not on-air in BeaconCore (Core only when fix valid).",
    },
    {
        "field_key": "short_id_collision",
        "scope_class": "Informative",
        "knowledge_category": "Identity",
        "status": "CodeNow",
        "owner": "Derived",
        "in_node_entry_struct": "Y",
        "node_entry_member": "short_id_collision",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot (flags bit3)",
        "exported_over_ble": "Y",
        "ble_record_offset": "10",
        "ble_bytes": "1",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "flags bit 0x08",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "1",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    {
        "field_key": "pos_age_s",
        "scope_class": "Core",
        "knowledge_category": "Position",
        "status": "CodeNow",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "pos_age_s",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "21",
        "ble_bytes": "2",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "Tail-1 pos quality; not in Core",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u16",
        "units_scaling": "seconds",
        "min_value": "0",
        "max_value": "65535",
        "bits_needed_min": "16",
        "tier": "B Tail-1",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Domain; not in BeaconCore payload (position_quality_v0).",
    },
    {
        "field_key": "last_rx_rssi",
        "scope_class": "Injected",
        "knowledge_category": "RadioContext",
        "status": "CodeNow",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_rx_rssi",
        "persisted": "Y",
        "persistence_notes": "BLE snapshot",
        "exported_over_ble": "Y",
        "ble_record_offset": "23",
        "ble_bytes": "1",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "link_metrics_v0",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "i8",
        "units_scaling": "dBm",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "8",
        "tier": "Derived/Injected",
        "default_cadence": "on RX",
        "trigger_type": "event-driven",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "rssiLast; receiver-side only.",
    },
    {
        "field_key": "last_seen_ms",
        "scope_class": "Injected",
        "knowledge_category": "Activity",
        "status": "CodeNow",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_seen_ms",
        "persisted": "Y",
        "persistence_notes": "internal; BLE exports last_seen_age_s derived",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u32",
        "units_scaling": "uptime ms",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "on RX",
        "trigger_type": "event-driven",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Exported as lastSeenAgeS (age_s) in BLE.",
    },
    {
        "field_key": "last_seen_age_s",
        "scope_class": "Derived",
        "knowledge_category": "Activity",
        "status": "CodeNow",
        "owner": "Derived",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "computed at export from last_seen_ms",
        "exported_over_ble": "Y",
        "ble_record_offset": "11",
        "ble_bytes": "2",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u16",
        "units_scaling": "(now_ms - last_seen_ms)/1000",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Derived for BLE; used for activity/grey.",
    },
    {
        "field_key": "is_grey",
        "scope_class": "Derived",
        "knowledge_category": "Activity",
        "status": "CodeNow",
        "owner": "Derived",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "computed at export",
        "exported_over_ble": "Y",
        "ble_record_offset": "10",
        "ble_bytes": "1",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "activity_state_v0",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "flags bit 0x04; age_s > expected_interval_s + grace_s",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "1",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    {
        "field_key": "in_use",
        "scope_class": "Informative",
        "knowledge_category": "LocalOnly",
        "status": "CodeNow",
        "owner": "AppLocal",
        "in_node_entry_struct": "Y",
        "node_entry_member": "in_use",
        "persisted": "N",
        "persistence_notes": "internal slot only",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Internal; not in BLE.",
    },
    # --- Tail-1 / Core linkage ---
    {
        "field_key": "ref_core_seq16",
        "scope_class": "Core",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_core_seq16 (stored); ref in payload",
        "persisted": "Y",
        "persistence_notes": "stored for Tail-1 match",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "tail1_packet_encoding_v0 §3",
        "wire_bytes_fixed": "2",
        "wire_optional": "MUST",
        "logical_type": "u16",
        "units_scaling": "Core linkage key",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "B Tail-1",
        "default_cadence": "every Core_Tail",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Back-reference to Core sample seq16; distinct from seq16 in Common.",
    },
    {
        "field_key": "posFlags",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "Superseded",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "pos_flags",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "tail1_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "bit0=position valid; 1-7 reserved",
        "min_value": "0",
        "max_value": "255",
        "bits_needed_min": "8",
        "tier": "B Tail-1",
        "default_cadence": "Every Tail-1",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0 canon. Superseded by pos_flags_small (v0.1 packed in pos_quality16).",
    },
    {
        "field_key": "sats",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "sats",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "tail1_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "satellite count; 0=not present",
        "min_value": "0",
        "max_value": "255",
        "bits_needed_min": "8",
        "tier": "B Tail-1",
        "default_cadence": "Every Tail-1",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0 canon. In v0.1 packed in pos_quality16; canonical field_key sats.",
    },
    {
        "field_key": "pos_sats",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "Superseded",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "alias for sats",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "B Tail-1",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Alias; superseded-by sats.",
    },
    {
        "field_key": "pos_quality16",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "2",
        "wire_optional": "OPT",
        "logical_type": "u16",
        "units_scaling": "packed: fix_type/sats/accuracy_bucket/pos_flags_small",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "B Tail-1",
        "default_cadence": "Every Tail-1",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0.1 container; replaces separate posFlags(1)+sats(1) in v0.",
    },
    {
        "field_key": "fix_type",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "enum",
        "units_scaling": "bits in pos_quality16: no_fix/2d/3d/reserved",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "2",
        "tier": "B Tail-1",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in pos_quality16.",
    },
    {
        "field_key": "pos_accuracy_bucket",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "bits in pos_quality16",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "3",
        "tier": "B Tail-1",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in pos_quality16.",
    },
    {
        "field_key": "pos_flags_small",
        "scope_class": "Operational",
        "knowledge_category": "Position",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Core_Tail",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "bits in pos_quality16; supersedes posFlags in v0.1",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "5",
        "tier": "B Tail-1",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Mapping from v0 posFlags; packed in pos_quality16.",
    },
    # --- Tail-2 Operational v0.1 ---
    {
        "field_key": "battery16",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "2",
        "wire_optional": "OPT",
        "logical_type": "u16",
        "units_scaling": "pct7+charging1+eta10m8",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "C Tail-2",
        "default_cadence": "on change + min_interval",
        "trigger_type": "periodic+threshold",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0.1 packed container.",
    },
    {
        "field_key": "battery_pct7",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "7 bits in battery16; 0-100",
        "min_value": "0",
        "max_value": "100",
        "bits_needed_min": "7",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in battery16.",
    },
    {
        "field_key": "charging1",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "bool",
        "units_scaling": "1 bit in battery16",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "1",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in battery16.",
    },
    {
        "field_key": "eta10m8",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "8 bits in battery16; minutes to empty, 0=N/A",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "8",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in battery16.",
    },
    {
        "field_key": "radio8",
        "scope_class": "Operational",
        "knowledge_category": "RadioContext",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "txPower4+throttle4",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "8",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0.1 container.",
    },
    {
        "field_key": "tx_power_step_u4",
        "scope_class": "Operational",
        "knowledge_category": "RadioContext",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "4 bits in radio8",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "4",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in radio8.",
    },
    {
        "field_key": "channel_throttle_step_u4",
        "scope_class": "Operational",
        "knowledge_category": "RadioContext",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "4 bits in radio8",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "4",
        "tier": "C Tail-2",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Packed in radio8.",
    },
    {
        "field_key": "uptime10m_u8",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "uptime in 10-minute units; masked-for-compare",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "8",
        "tier": "C Tail-2",
        "default_cadence": "on change + min_interval",
        "trigger_type": "periodic+threshold",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0.1; eligibility snapshot mask.",
    },
    {
        "field_key": "role_id",
        "scope_class": "Informative",
        "knowledge_category": "Identity",
        "status": "WIP",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Informative",
        "on_air_contract_ref": "packet_sets_v0_1",
        "wire_bytes_fixed": "",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "role identifier",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "TODO",
        "tier": "C Tail-2",
        "default_cadence": "periodic + changed-boost",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "v0.1 new; Informative. CONFLICT: hw/fw remain u16 in canon.",
    },
    # --- Tail-2 Operational ---
    {
        "field_key": "batteryPercent",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "battery_percent",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "tail2_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "0-100%; 0xFF=not present",
        "min_value": "0",
        "max_value": "100",
        "bits_needed_min": "7",
        "tier": "C Tail-2",
        "default_cadence": "on change + at forced Core",
        "trigger_type": "periodic+threshold",
        "threshold_rule": "battery delta",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    {
        "field_key": "uptimeSec",
        "scope_class": "Operational",
        "knowledge_category": "Telemetry/Health",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "uptime_sec",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Operational",
        "on_air_contract_ref": "tail2_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "4",
        "wire_optional": "OPT",
        "logical_type": "u32",
        "units_scaling": "seconds; 0xFFFFFFFF=not present",
        "min_value": "0",
        "max_value": "4294967295",
        "bits_needed_min": "32",
        "tier": "B Tail-1",
        "default_cadence": "on change + at forced Core",
        "trigger_type": "periodic+threshold",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "field_cadence: Tier B; packet is Node_Operational (0x04).",
    },
    # --- Informative (0x05) ---
    {
        "field_key": "maxSilence10s",
        "scope_class": "Informative",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "max_silence_10s",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Informative",
        "on_air_contract_ref": "info_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "10s steps; 0=absent",
        "min_value": "0",
        "max_value": "255",
        "bits_needed_min": "8",
        "tier": "C Tail-2",
        "default_cadence": "on change + every 10 min",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Liveness hint; MUST NOT send on every Operational. Tier C.",
    },
    {
        "field_key": "hwProfileId",
        "scope_class": "Informative",
        "knowledge_category": "Identity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "hw_profile_id",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Informative",
        "on_air_contract_ref": "info_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "2",
        "wire_optional": "OPT",
        "logical_type": "u16",
        "units_scaling": "0xFFFF=not present",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "C Tail-2",
        "default_cadence": "on change + every 10 min",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    {
        "field_key": "fwVersionId",
        "scope_class": "Informative",
        "knowledge_category": "Identity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "Y",
        "node_entry_member": "fw_version_id",
        "persisted": "Y",
        "persistence_notes": "in NodeEntry",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Node_Informative",
        "on_air_contract_ref": "info_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "2",
        "wire_optional": "OPT",
        "logical_type": "u16",
        "units_scaling": "0xFFFF=not present",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "16",
        "tier": "C Tail-2",
        "default_cadence": "on change + every 10 min",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "",
    },
    # --- Alive ---
    {
        "field_key": "aliveStatus",
        "scope_class": "Core",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "Y",
        "packet_name_canon": "Alive",
        "on_air_contract_ref": "alive_packet_encoding_v0 §3.2",
        "wire_bytes_fixed": "1",
        "wire_optional": "OPT",
        "logical_type": "u8",
        "units_scaling": "0x00=alive_no_fix",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "8",
        "tier": "A Core",
        "default_cadence": "no-fix liveness",
        "trigger_type": "periodic",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Alive packet optional byte.",
    },
    # --- Internal Tail-1 variant-2 ---
    {
        "field_key": "last_applied_tail_ref_core_seq16",
        "scope_class": "Informative",
        "knowledge_category": "Activity",
        "status": "CodeNow",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_applied_tail_ref_core_seq16",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "tail1_packet_encoding_v0; at most one Tail per Core",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u16",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Variant 2: dedupe second Tail-1 for same ref_core_seq16.",
    },
    # --- Canon inventory: receiver-derived / not yet in BLE ---
    {
        "field_key": "lastRxAt",
        "scope_class": "Injected",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "Y",
        "node_entry_member": "last_seen_ms",
        "persisted": "Y",
        "persistence_notes": "same as last_seen_ms in code",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "link-telemetry-minset-v0 Table A",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "timestamp",
        "units_scaling": "receiver clock",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "on RX",
        "trigger_type": "event-driven",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Canon name; firmware uses last_seen_ms.",
    },
    {
        "field_key": "snrLast",
        "scope_class": "Injected",
        "knowledge_category": "RadioContext",
        "status": "Canon",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "TODO: add to NodeEntry/BLE if needed",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "link_metrics_v0",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "numeric",
        "units_scaling": "dB",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "TODO",
        "tier": "Derived/Injected",
        "default_cadence": "on RX",
        "trigger_type": "event-driven",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Not in current BLE record.",
    },
    {
        "field_key": "activityState",
        "scope_class": "Derived",
        "knowledge_category": "Activity",
        "status": "Canon",
        "owner": "Derived",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "activity_state_v0",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "enum",
        "units_scaling": "Unknown/Active/Stale/Lost",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "derived on RX",
        "trigger_type": "",
        "threshold_rule": "T_active, T_stale params",
        "staleness_ttl_hint": "TODO",
        "notes": "",
    },
    {
        "field_key": "PositionQuality",
        "scope_class": "Derived",
        "knowledge_category": "Position",
        "status": "Canon",
        "owner": "Derived",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "position_quality_v0",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "derived",
        "units_scaling": "Core + Tail-1 posFlags/sats + age",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Derived; sent components posFlags, sats in Tail-1.",
    },
    {
        "field_key": "networkName",
        "scope_class": "User",
        "knowledge_category": "Identity",
        "status": "Idea",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "index §4",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "string",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "NOT sent in v0 beacon; future session-join.",
    },
    {
        "field_key": "localAlias",
        "scope_class": "User",
        "knowledge_category": "LocalOnly",
        "status": "Canon",
        "owner": "AppLocal",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "Y",
        "persistence_notes": "app local storage",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "inventory",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "string",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "User-defined on phone; not over radio.",
    },
    # --- Mesh_future (from mesh concept + meshtastic research) ---
    {
        "field_key": "last_direct_time",
        "scope_class": "Mesh_future",
        "knowledge_category": "RadioContext",
        "status": "Mesh_future",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "naviga_mesh_protocol_concept_v1_4.md",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "timestamp",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Time of last direct RX from this node; mesh concept. Non-goal v0.",
    },
    {
        "field_key": "snr_direct",
        "scope_class": "Mesh_future",
        "knowledge_category": "RadioContext",
        "status": "Mesh_future",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "meshtastic research",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "numeric",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Direct-link SNR; Mesh_future. Non-goal v0.",
    },
    {
        "field_key": "rssi_direct",
        "scope_class": "Mesh_future",
        "knowledge_category": "RadioContext",
        "status": "Mesh_future",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "meshtastic research",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "numeric",
        "units_scaling": "",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Direct-link RSSI; Mesh_future. Non-goal v0.",
    },
    {
        "field_key": "hops",
        "scope_class": "Mesh_future",
        "knowledge_category": "Routing/Mesh",
        "status": "Mesh_future",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "meshtastic-nodetable.md §3",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "hops_away",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "No mesh routing in Naviga v0.",
    },
    {
        "field_key": "next_hop",
        "scope_class": "Mesh_future",
        "knowledge_category": "Routing/Mesh",
        "status": "Mesh_future",
        "owner": "ReceiverInjected",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "meshtastic-nodetable.md §3",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "u8",
        "units_scaling": "last byte of node num",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "No mesh routing in Naviga v0.",
    },
    {
        "field_key": "pos_history",
        "scope_class": "Mesh_future",
        "knowledge_category": "Position",
        "status": "Mesh_future",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "naviga_mesh_protocol_concept_v1_4.md",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "array",
        "units_scaling": "short history of positions",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Optional pos_history_X; mesh concept. Non-goal v0.",
    },
    {
        "field_key": "role_params",
        "scope_class": "Mesh_future",
        "knowledge_category": "Activity",
        "status": "Mesh_future",
        "owner": "NodeOwned",
        "in_node_entry_struct": "N",
        "node_entry_member": "",
        "persisted": "N",
        "persistence_notes": "",
        "exported_over_ble": "N",
        "ble_record_offset": "",
        "ble_bytes": "",
        "sent_on_air": "N",
        "packet_name_canon": "",
        "on_air_contract_ref": "naviga_mesh_protocol_concept_v1_4.md",
        "wire_bytes_fixed": "",
        "wire_optional": "",
        "logical_type": "enum/params",
        "units_scaling": "role_pos_update_interval_X etc",
        "min_value": "",
        "max_value": "",
        "bits_needed_min": "",
        "tier": "Derived/Injected",
        "default_cadence": "",
        "trigger_type": "",
        "threshold_rule": "",
        "staleness_ttl_hint": "",
        "notes": "Role-based delivery params; mesh concept. Non-goal v0.",
    },
]

PACKETS_HEADERS = [
    "packet_name_canon",
    "legacy_name",
    "purpose",
    "max_payload_budget_by_profile",
    "cadence_default",
    "gating_rule",
    "fields_included",
]

PACKETS_ROWS = [
    {
        "packet_name_canon": "Node_Core_Pos",
        "legacy_name": "BEACON_CORE",
        "purpose": "Minimal sample: WHO + WHERE + freshness. Core only with valid fix.",
        "max_payload_budget_by_profile": "LongDist 24, Default 32, Fast 40 (payload only)",
        "cadence_default": "every beacon tick when position valid",
        "gating_rule": "only with valid GNSS fix",
        "fields_included": "payloadVersion, node_id, seq16, positionLat, positionLon",
    },
    {
        "packet_name_canon": "Alive",
        "legacy_name": "BEACON_ALIVE",
        "purpose": "No-fix liveness; identity + seq16 only. Alive-bearing, non-position-bearing.",
        "max_payload_budget_by_profile": "9–10 B payload",
        "cadence_default": "when no fix, within maxSilence",
        "gating_rule": "alive when no fix",
        "fields_included": "payloadVersion, node_id, seq16, aliveStatus (optional)",
    },
    {
        "packet_name_canon": "Node_Core_Tail",
        "legacy_name": "BEACON_TAIL1",
        "purpose": "Core-attached extension; qualifies one Core sample. Optional, loss-tolerant.",
        "max_payload_budget_by_profile": "11–13 B payload",
        "cadence_default": "Every Tail-1 (when position valid)",
        "gating_rule": "ref_core_seq16 must match lastCoreSeq",
        "fields_included": "payloadVersion, node_id, seq16, ref_core_seq16, posFlags (opt), sats (opt)",
    },
    {
        "packet_name_canon": "Node_Operational",
        "legacy_name": "BEACON_TAIL2",
        "purpose": "Dynamic runtime: battery, uptime. Optional, loss-tolerant.",
        "max_payload_budget_by_profile": "9–14 B payload",
        "cadence_default": "on change + at forced Core",
        "gating_rule": "no CoreRef",
        "fields_included": "payloadVersion, node_id, seq16, batteryPercent (opt), uptimeSec (opt)",
    },
    {
        "packet_name_canon": "Node_Informative",
        "legacy_name": "BEACON_INFO",
        "purpose": "Static/config: maxSilence, hwProfileId, fwVersionId. Optional, loss-tolerant.",
        "max_payload_budget_by_profile": "9–14 B payload",
        "cadence_default": "on change + every 10 min",
        "gating_rule": "no CoreRef; MUST NOT send on every Operational",
        "fields_included": "payloadVersion, node_id, seq16, maxSilence10s (opt), hwProfileId (opt), fwVersionId (opt)",
    },
]

SOURCES_HEADERS = ["path", "description"]
SOURCES_ROWS = [
    ("docs/product/areas/nodetable/index.md", "NodeTable hub; scope, invariants, contract/policy links."),
    ("docs/product/areas/nodetable/contract/beacon_payload_encoding_v0.md", "Beacon byte layout; Common prefix; Core/Tail/Operational/Informative."),
    ("docs/product/areas/nodetable/contract/alive_packet_encoding_v0.md", "Alive packet (0x02); no-fix liveness; seq16."),
    ("docs/product/areas/nodetable/contract/tail1_packet_encoding_v0.md", "Core_Tail (0x03); ref_core_seq16; posFlags, sats."),
    ("docs/product/areas/nodetable/contract/tail2_packet_encoding_v0.md", "Operational (0x04); batteryPercent, uptimeSec."),
    ("docs/product/areas/nodetable/contract/info_packet_encoding_v0.md", "Informative (0x05); maxSilence10s, hwProfileId, fwVersionId."),
    ("docs/product/areas/nodetable/contract/link-telemetry-minset-v0.md", "Link/Metrics & Telemetry minset; ownership, persisted vs derived."),
    ("docs/product/areas/nodetable/policy/field_cadence_v0.md", "Tiers A/B/C; cadences; degrade order; Operational vs Informative."),
    ("docs/product/areas/nodetable/policy/nodetable_fields_inventory_v0.md", "Fields inventory; coupling; Tier/cadence/placement worksheet."),
    ("docs/product/areas/nodetable/policy/activity_state_v0.md", "Activity/presence: Unknown/Active/Stale/Lost; thresholds."),
    ("docs/product/areas/nodetable/policy/link_metrics_v0.md", "Receiver-derived: rssiLast/snrLast, rssiRecent/snrRecent."),
    ("docs/product/areas/nodetable/policy/position_quality_v0.md", "Position quality; Tail-1 posFlags/sats; PositionQuality derived."),
    ("firmware/src/domain/node_table.h", "NodeEntry struct; NodeTable class; kRecordBytes=26."),
    ("firmware/src/domain/node_table.cpp", "get_page/get_snapshot_page BLE layout; upsert_remote; apply_tail1/tail2/info."),
    ("docs/product/wip/areas/nodetable/research/naviga-current-state.md", "BLE 26-byte record layout; NodeRecordV1; write/read paths."),
    ("docs/product/wip/areas/nodetable/research/meshastic-nodetable.md", "Meshtastic NodeDB categories; transferability; hops_away, next_hop, last_heard."),
    ("docs/product/naviga_mesh_protocol_concept_v1_4.md", "Mesh concept; last_direct_time, pos_history, role params (future)."),
    ("app/lib/features/connect/connect_controller.dart", "NodeRecordV1; BleNodeTableParser.parsePage; 26-byte record offsets."),
    ("docs/product/wip/areas/nodetable/policy/tx_priority_and_arbitration_v0_1.md", "TX priority P0-P3; coalesce_key; hybrid expired_counter (WIP)."),
    ("docs/product/wip/areas/nodetable/policy/packet_sets_v0_1.md", "Packet sets v0.1; Core_Tail/Operational/Informative payloads; CONFLICT HW/FW width."),
]


def row_to_list(row: dict, headers: list) -> list:
    return [row.get(h, "") for h in headers]


def write_csv(path: Path, headers: list, rows: list) -> None:
    """Write CSV with UTF-8, newline='', QUOTE_MINIMAL. rows: list of sequences (same length as headers)."""
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(headers)
        writer.writerows(rows)


def main() -> None:
    # Deterministic ordering: same for XLSX and CSV (documented in README).
    fields_sorted = sorted(
        FIELDS_ROWS,
        key=lambda r: (r.get("status", ""), r.get("scope_class", ""), r.get("field_key", "")),
    )
    packets_sorted = sorted(PACKETS_ROWS, key=lambda r: r.get("packet_name_canon", ""))
    sources_sorted = sorted(SOURCES_ROWS, key=lambda t: t[0])  # by path

    MASTER_TABLE_DIR.mkdir(parents=True, exist_ok=True)

    # XLSX
    wb = Workbook()
    ws_fields = wb.active
    ws_fields.title = "Fields"
    ws_fields.append(FIELDS_HEADERS)
    for r in fields_sorted:
        ws_fields.append(row_to_list(r, FIELDS_HEADERS))

    ws_packets = wb.create_sheet("Packets", 1)
    ws_packets.append(PACKETS_HEADERS)
    for r in packets_sorted:
        ws_packets.append(row_to_list(r, PACKETS_HEADERS))

    ws_sources = wb.create_sheet("Sources", 2)
    ws_sources.append(SOURCES_HEADERS)
    for path, desc in sources_sorted:
        ws_sources.append([path, desc])

    wb.save(OUTPUT_XLSX)
    print(f"Wrote {OUTPUT_XLSX}")

    # CSV (mirror sheets: same columns, same row count)
    write_csv(
        OUTPUT_CSV_FIELDS,
        FIELDS_HEADERS,
        [row_to_list(r, FIELDS_HEADERS) for r in fields_sorted],
    )
    print(f"Wrote {OUTPUT_CSV_FIELDS}")
    write_csv(
        OUTPUT_CSV_PACKETS,
        PACKETS_HEADERS,
        [row_to_list(r, PACKETS_HEADERS) for r in packets_sorted],
    )
    print(f"Wrote {OUTPUT_CSV_PACKETS}")
    write_csv(
        OUTPUT_CSV_SOURCES,
        SOURCES_HEADERS,
        [list(row) for row in sources_sorted],
    )
    print(f"Wrote {OUTPUT_CSV_SOURCES}")


if __name__ == "__main__":
    main()
