# Minimal yamllint config for .github/workflows (Issue #5).
# Relax line-length; disable document-start and truthy for GitHub Actions compatibility.
extends: default
rules:
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  document-start: disable
  truthy: disable
